### ISSUE TITLE
Got an Error here

### ISSUE THREAD

**Issue by bararchy** [mfazekas/test-net-ssh-fwd#1]
```
E, [2015-01-28T16:28:30.144668 #37609] ERROR -- : Got exception: #<NoMethodError: undefined method `server_version' for #<Net::SSH::Transport::ServerSession:0x0000000264a080>>
E, [2015-01-28T16:28:30.144827 #37609] ERROR -- : ["/usr/local/rvm/gems/ruby-head/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:359:in `exchange_keys'", "/usr/local/rvm/gems/ruby-head/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:200:in `proceed!'", "/usr/local/rvm/gems/ruby-head/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:148:in `accept_kexinit'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:275:in `block in poll_message'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:299:in `block in loop'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:299:in `loop'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:299:in `loop'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:252:in `poll_message'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:290:in `block in wait'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:299:in `block in loop'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:299:in `loop'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:299:in `loop'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:288:in `wait'", "/opt/Zakif/Libs/net-ssh/lib/net/ssh/transport/server_session.rb:74:in `initialize'", "/opt/Zakif/Libs/lib/sshfwd/server.rb:272:in `new'", "/opt/Zakif/Libs/lib/sshfwd/server.rb:272:in `block (2 levels) in run'"]
```

**Comment by bararchy** [comment]
Is this happening because I have another version of net-ssh gem installed ?

**Comment by mfazekas** [comment]
yes somehow it's finding the /usr/local/rvm/gems/ruby-head/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb.   instead of my version of net-ssh
